# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/db_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(Form)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add_person = QtWidgets.QPushButton(self.tab)
        self.btn_add_person.setObjectName("btn_add_person")
        self.horizontalLayout.addWidget(self.btn_add_person)
        self.btn_edit_person = QtWidgets.QPushButton(self.tab)
        self.btn_edit_person.setObjectName("btn_edit_person")
        self.horizontalLayout.addWidget(self.btn_edit_person)
        self.btn_delete_person = QtWidgets.QPushButton(self.tab)
        self.btn_delete_person.setObjectName("btn_delete_person")
        self.horizontalLayout.addWidget(self.btn_delete_person)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.table_people = QtWidgets.QTableWidget(self.tab)
        self.table_people.setObjectName("table_people")
        self.table_people.setColumnCount(0)
        self.table_people.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_people)
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_emotion = QtWidgets.QPushButton(self.tab_2)
        self.btn_add_emotion.setObjectName("btn_add_emotion")
        self.horizontalLayout_2.addWidget(self.btn_add_emotion)
        self.btn_edit_emotion = QtWidgets.QPushButton(self.tab_2)
        self.btn_edit_emotion.setObjectName("btn_edit_emotion")
        self.horizontalLayout_2.addWidget(self.btn_edit_emotion)
        self.btn_delete_emotion = QtWidgets.QPushButton(self.tab_2)
        self.btn_delete_emotion.setObjectName("btn_delete_emotion")
        self.horizontalLayout_2.addWidget(self.btn_delete_emotion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.table_emotions = QtWidgets.QTableWidget(self.tab_2)
        self.table_emotions.setObjectName("table_emotions")
        self.table_emotions.setColumnCount(0)
        self.table_emotions.setRowCount(0)
        self.verticalLayout_3.addWidget(self.table_emotions)
        self.tab_widget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab_widget)

        self.retranslateUi(Form)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_add_person.setText(_translate("Form", "Добавить"))
        self.btn_edit_person.setText(_translate("Form", "Изменить"))
        self.btn_delete_person.setText(_translate("Form", "Удалить"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("Form", "Люди"))
        self.btn_add_emotion.setText(_translate("Form", "Добавить"))
        self.btn_edit_emotion.setText(_translate("Form", "Изменить"))
        self.btn_delete_emotion.setText(_translate("Form", "Удалить"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("Form", "Эмоции"))
